### ISSUE TITLE
How do I get started using it?

### ISSUE THREAD

**Issue by svavantsa** [WesTower/py-quickbase#1]
Can you please include instructions on how to "install" this? Is this a module, package or do we just need to download the main quickbase.py file and get started?

**Comment by mpedersen** [comment]
This is an internally developed API for integrating our Python apps with our QuickBase database.  I don't know when it was last maintained, or frankly why it was posted publicly, but it shouldn't have any sensitive data, so I suppose that the intent was simply to share and invite suggestions.

I cannot offer any advice on how to install or use it.  I never liked Python, and created my own Java version to do similar work.  WesTower was purchased by another company about 3 years ago.  Our last Python developer left about a year ago.

**Comment by svavantsa** [comment]
Martin,

Thanks for your quick response. I will figure it out from the docs
folder. Actually this is quite a good SDK that I plan to integrate our
QuickBase apps with Python scripts for automating certain tasks.

On 7/12/18, Martin Alan Pedersen <notifications@github.com> wrote:
> This is an internally developed API for integrating our Python apps with our
> QuickBase database.  I don't know when it was last maintained, or frankly
> why it was posted publicly, but it shouldn't have any sensitive data, so I
> suppose that the intent was simply to share and invite suggestions.
>
> I cannot offer any advice on how to install or use it.  I never liked
> Python, and created my own Java version to do similar work.  WesTower was
> purchased by another company about 3 years ago.  Our last Python developer
> left about a year ago.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/WesTower/py-quickbase/issues/1#issuecomment-404655296


-- 

Thank You,

Surya Avantsa
*908-705-5573*
